var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/widget/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1y_e7kn._.js")
R.c("server/chunks/ssr/03md_next_dist_1w29_li._.js")
R.c("server/chunks/ssr/03md_next_dist_20c-zfy._.js")
R.c("server/chunks/ssr/03md_next_dist_esm_build_templates_app-page_1py8l18.js")
R.c("server/chunks/ssr/[root-of-the-server]__0flv7u5._.js")
R.c("server/chunks/ssr/03md_next_dist_0wguxao._.js")
R.c("server/chunks/ssr/node_modules__pnpm_0-m25ik._.js")
R.c("server/chunks/ssr/src_app_11khhn1._.js")
R.c("server/chunks/ssr/03md_next_dist_client_components_05kfeha._.js")
R.c("server/chunks/ssr/03md_next_dist_client_components_builtin_forbidden_0hs3de_.js")
R.c("server/chunks/ssr/03md_next_dist_client_components_builtin_unauthorized_0p6_l6w.js")
R.c("server/chunks/ssr/src_app_global-error_tsx_1o3h_re._.js")
R.c("server/chunks/ssr/_next-internal_server_app_widget_page_actions_16_ikne.js")
R.m(341468)
module.exports=R.m(341468).exports
