var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/integrations/orders/webhook/route.js")
R.c("server/chunks/src_lib_automations_engine_ts_0-p64u-._.js")
R.c("server/chunks/[root-of-the-server]__0r49k0k._.js")
R.c("server/chunks/[root-of-the-server]__12uk597._.js")
R.c("server/chunks/0peu_@supabase_supabase-js_dist_index_mjs_0aqd_3s._.js")
R.c("server/chunks/node_modules__pnpm_0y91-f-._.js")
R.c("server/chunks/_1akliim._.js")
R.c("server/chunks/_next-internal_server_app_api_integrations_orders_webhook_route_actions_0meggmc.js")
R.m(453607)
module.exports=R.m(453607).exports
