// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/agents" | "/agents/[id]" | "/analytics" | "/automations" | "/automations/[id]" | "/customers" | "/customers/[id]" | "/dashboard" | "/experiments" | "/inbox" | "/knowledge" | "/login" | "/login/mfa" | "/onboarding" | "/rate/[token]" | "/reset-password" | "/rules" | "/settings" | "/simulate" | "/team" | "/tickets" | "/widget"
type AppRouteHandlerRoutes = "/api/ai/stream" | "/api/channels/chat" | "/api/channels/email" | "/api/export" | "/api/integrations/orders/webhook" | "/api/jobs/process" | "/api/stripe/webhook" | "/auth/callback"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/agents": {}
  "/agents/[id]": { "id": string; }
  "/analytics": {}
  "/api/ai/stream": {}
  "/api/channels/chat": {}
  "/api/channels/email": {}
  "/api/export": {}
  "/api/integrations/orders/webhook": {}
  "/api/jobs/process": {}
  "/api/stripe/webhook": {}
  "/auth/callback": {}
  "/automations": {}
  "/automations/[id]": { "id": string; }
  "/customers": {}
  "/customers/[id]": { "id": string; }
  "/dashboard": {}
  "/experiments": {}
  "/inbox": {}
  "/knowledge": {}
  "/login": {}
  "/login/mfa": {}
  "/onboarding": {}
  "/rate/[token]": { "token": string; }
  "/reset-password": {}
  "/rules": {}
  "/settings": {}
  "/simulate": {}
  "/team": {}
  "/tickets": {}
  "/widget": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
